spring.datasource.url=jdbc:postgresql://aws-1-eu-central-1.pooler.supabase.com:5432/postgres?user=postgres.lsmtnupkbbnyttxkzrhb&password=r2bsystemsisthebest!
spring.datasource.username=postgres
spring.datasource.password=r2bsystemsisthebest!
server.port=8081

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.thymeleaf.cache=false

spring.web.resources.static-locations=classpath:/static/